import { MigrationInterface, QueryRunner } from "typeorm";

export class Migration1715415858760 implements MigrationInterface {
    name = 'Migration1715415858760'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "permission" ("id" SERIAL NOT NULL, "permission_name" character varying(255) NOT NULL, "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_3b8b97af9d9d8807e41e6f48362" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "role" ("id" SERIAL NOT NULL, "role_name" character varying(255) NOT NULL, "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b36bcfe02fc8de3c57a8b2391c2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."order_payment_method_enum" AS ENUM('vnpay')`);
        await queryRunner.query(`CREATE TABLE "order" ("_id" SERIAL NOT NULL, "total" numeric NOT NULL DEFAULT '0', "payment_status" boolean NOT NULL DEFAULT false, "payment_method" "public"."order_payment_method_enum" NOT NULL DEFAULT 'vnpay', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "user_id" uuid, CONSTRAINT "PK_73c5a7089b00fa8b32ff1733a12" PRIMARY KEY ("_id"))`);
        await queryRunner.query(`CREATE TABLE "section" ("_id" SERIAL NOT NULL, "section_name" character varying(100) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "course_id" integer, CONSTRAINT "PK_34df428eb130777a61fcf7dc92b" PRIMARY KEY ("_id"))`);
        await queryRunner.query(`CREATE TABLE "course_bookmark" ("_id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "course_id" integer, "user_id" uuid, CONSTRAINT "PK_2fd4d4da7dd40e4d1d8ca52ce69" PRIMARY KEY ("_id"))`);
        await queryRunner.query(`CREATE TABLE "user_course" ("_id" SERIAL NOT NULL, "current_section" integer NOT NULL DEFAULT '1', "current_lecture" integer NOT NULL DEFAULT '1', "progress" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "course_id" integer, "user_id" uuid, CONSTRAINT "PK_0357ff65962b2e38e0b59540356" PRIMARY KEY ("_id"))`);
        await queryRunner.query(`CREATE TABLE "course" ("_id" SERIAL NOT NULL, "course_name" character varying(255) NOT NULL, "description" text, "price" integer NOT NULL, "total_duration" numeric(10,2) NOT NULL DEFAULT '0', "thumbnail_url" text, "expired_date" date, "category_id" integer, "sub_category_id" integer, "teacher_id" character varying NOT NULL, "is_public" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ab9e0eff3d917f26c04846d8224" PRIMARY KEY ("_id"))`);
        await queryRunner.query(`CREATE TABLE "comment" ("_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "author_name" character varying NOT NULL, "author_thumbnail" text, "content" text NOT NULL, "like_count" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "lecture_id" integer, "user_id" uuid, CONSTRAINT "PK_f069f9101854625792dca32f117" PRIMARY KEY ("_id"))`);
        await queryRunner.query(`CREATE TABLE "lecture_quizz" ("_id" SERIAL NOT NULL, "quizz_id" integer NOT NULL, "question_time" numeric NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "lecture_id" integer, CONSTRAINT "PK_a25d3491005e737bbfea3d69d65" PRIMARY KEY ("_id"))`);
        await queryRunner.query(`CREATE TYPE "public"."lecture_lecture_type_enum" AS ENUM('VIDEO', 'EXAM')`);
        await queryRunner.query(`CREATE TABLE "lecture" ("_id" SERIAL NOT NULL, "lecture_name" character varying(255) NOT NULL, "lecture_type" "public"."lecture_lecture_type_enum" NOT NULL, "duration" integer, "url" character varying, "slug" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "exam_id" integer, "section_id" integer, CONSTRAINT "UQ_dff3c45c6a2688bdef948f158a7" UNIQUE ("slug"), CONSTRAINT "PK_8389063f0374b5ccdf2b4dc7250" PRIMARY KEY ("_id"))`);
        await queryRunner.query(`CREATE TABLE "order_detail" ("_id" SERIAL NOT NULL, "price" numeric NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "order_id" integer, "cart_id" integer, "course_id" integer, CONSTRAINT "PK_293190b58b6a3b558bbe018967f" PRIMARY KEY ("_id"))`);
        await queryRunner.query(`CREATE TABLE "cart" ("_id" SERIAL NOT NULL, "discount" numeric(10,2) NOT NULL DEFAULT '0', "status" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "user_id" uuid, "course_id" integer, CONSTRAINT "PK_ec117221695fb740d8cb2f04868" PRIMARY KEY ("_id"))`);
        await queryRunner.query(`CREATE TABLE "user_quizz" ("_id" SERIAL NOT NULL, "status" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "user_id" uuid, "quizz_id" integer, CONSTRAINT "PK_c58c51adb497fbfa5345bf38065" PRIMARY KEY ("_id"))`);
        await queryRunner.query(`CREATE TABLE "quizz" ("_id" SERIAL NOT NULL, "title" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "teacher_id" character varying NOT NULL, CONSTRAINT "PK_fa5d2b8b5d1e5a4542f72432011" PRIMARY KEY ("_id"))`);
        await queryRunner.query(`CREATE TYPE "public"."question_question_level_enum" AS ENUM('Nhận biết', 'Thông hiểu', 'Vận dụng', 'Vận dụng cao')`);
        await queryRunner.query(`CREATE TYPE "public"."question_answer_type_enum" AS ENUM('Chọn nhiều', 'Chọn 1')`);
        await queryRunner.query(`CREATE TABLE "question" ("_id" SERIAL NOT NULL, "question_title" character varying NOT NULL, "question_level" "public"."question_question_level_enum", "answer_type" "public"."question_answer_type_enum" NOT NULL DEFAULT 'Chọn 1', "answers" character varying array NOT NULL, "correct_answers" integer array NOT NULL, "answer_explain" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "exam_id" integer, "quizz_id" integer, CONSTRAINT "PK_7172ea1d3c8db07e93733f22e92" PRIMARY KEY ("_id"))`);
        await queryRunner.query(`CREATE TABLE "user_exam" ("_id" SERIAL NOT NULL, "complete_time" numeric(10,2) NOT NULL, "corrects" integer NOT NULL DEFAULT '0', "total_questions" integer NOT NULL DEFAULT '0', "score" numeric NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "user_id" uuid, "exam_id" integer, CONSTRAINT "PK_7bbe53bc7e3059be70657ae5186" PRIMARY KEY ("_id"))`);
        await queryRunner.query(`CREATE TABLE "exam" ("_id" SERIAL NOT NULL, "exam_title" character varying(255) NOT NULL, "category_id" integer NOT NULL, "sub_category_id" integer NOT NULL, "time" integer NOT NULL, "teacher_id" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_676e1d55807c98f96489136c0e6" PRIMARY KEY ("_id"))`);
        await queryRunner.query(`CREATE TYPE "public"."blog_status_enum" AS ENUM('PENDING', 'ACCEPTED', 'DECLINED')`);
        await queryRunner.query(`CREATE TABLE "blog" ("_id" SERIAL NOT NULL, "title" character varying NOT NULL, "tags" character varying array NOT NULL, "content" text NOT NULL, "preview_content" character varying NOT NULL, "status" "public"."blog_status_enum" NOT NULL DEFAULT 'PENDING', "decline_reason" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "user_id" uuid, CONSTRAINT "PK_b3127a17453bcf20f077bd89fc8" PRIMARY KEY ("_id"))`);
        await queryRunner.query(`CREATE TABLE "user" ("_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "fullname" character varying(255), "email" character varying(255) NOT NULL, "username" character varying(255), "password" character varying(255) NOT NULL, "phone" character varying(255), "gender" boolean, "birth_date" date, "grade_id" integer, "preferred_subjects" integer array, "subject_group_id" integer, "is_verify_email" boolean NOT NULL DEFAULT false, "is_disabled" boolean NOT NULL DEFAULT false, "is_deteled" boolean NOT NULL DEFAULT false, "memo" text, "email_verify_code" character varying(255), "refresh_token" character varying, "avatar" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "address_id" integer, CONSTRAINT "REL_302d96673413455481d5ff4022" UNIQUE ("address_id"), CONSTRAINT "PK_457bfa3e35350a716846b03102d" PRIMARY KEY ("_id"))`);
        await queryRunner.query(`CREATE TABLE "address" ("_id" SERIAL NOT NULL, "province" integer, "district" integer, "detail" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_eadc386b023af2ddcf2e1bd94ec" PRIMARY KEY ("_id"))`);
        await queryRunner.query(`CREATE TABLE "category" ("_id" SERIAL NOT NULL, "category_name" character varying NOT NULL, "description" text, "list_courses" integer array, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "category_id" integer, CONSTRAINT "PK_0d6721292a14c4041a79fb021fb" PRIMARY KEY ("_id"))`);
        await queryRunner.query(`CREATE TABLE "subject" ("_id" SERIAL NOT NULL, "subject_name" character varying(255) NOT NULL, "include_courses" text array, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_2ca5d4ef9f9901d3f03f0d0ae20" PRIMARY KEY ("_id"))`);
        await queryRunner.query(`CREATE TABLE "subject_group" ("_id" SERIAL NOT NULL, "subject_group_name" character varying(255), "include_subjects" integer array, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_91930f71348b4fb65ddae12c11e" PRIMARY KEY ("_id"))`);
        await queryRunner.query(`CREATE TABLE "role_permissions_permission" ("roleId" integer NOT NULL, "permissionId" integer NOT NULL, CONSTRAINT "PK_b817d7eca3b85f22130861259dd" PRIMARY KEY ("roleId", "permissionId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b36cb2e04bc353ca4ede00d87b" ON "role_permissions_permission" ("roleId") `);
        await queryRunner.query(`CREATE INDEX "IDX_bfbc9e263d4cea6d7a8c9eb3ad" ON "role_permissions_permission" ("permissionId") `);
        await queryRunner.query(`CREATE TABLE "user_roles_role" ("user_id" uuid NOT NULL, "roleId" integer NOT NULL, CONSTRAINT "PK_c7365efb1c7b66b474c0e95dd70" PRIMARY KEY ("user_id", "roleId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_09d115a69b6014d324d592f9c4" ON "user_roles_role" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_4be2f7adf862634f5f803d246b" ON "user_roles_role" ("roleId") `);
        await queryRunner.query(`ALTER TABLE "order" ADD CONSTRAINT "FK_199e32a02ddc0f47cd93181d8fd" FOREIGN KEY ("user_id") REFERENCES "user"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "section" ADD CONSTRAINT "FK_7e12912705e3430a0bd74dad81f" FOREIGN KEY ("course_id") REFERENCES "course"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "course_bookmark" ADD CONSTRAINT "FK_fafd38e7eaaa2dc5b0ac841d935" FOREIGN KEY ("course_id") REFERENCES "course"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "course_bookmark" ADD CONSTRAINT "FK_d5619bd83409d0f260d9cd959f3" FOREIGN KEY ("user_id") REFERENCES "user"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_course" ADD CONSTRAINT "FK_a17a0128f2f4fbb56ca04a07036" FOREIGN KEY ("course_id") REFERENCES "course"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_course" ADD CONSTRAINT "FK_8abb4cbd80ac598dbe7c4dd8ce2" FOREIGN KEY ("user_id") REFERENCES "user"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comment" ADD CONSTRAINT "FK_c86c5b7d5079786fb840989975e" FOREIGN KEY ("lecture_id") REFERENCES "lecture"("_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comment" ADD CONSTRAINT "FK_bbfe153fa60aa06483ed35ff4a7" FOREIGN KEY ("user_id") REFERENCES "user"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lecture_quizz" ADD CONSTRAINT "FK_2c90f00c429114649d5a0df9898" FOREIGN KEY ("lecture_id") REFERENCES "lecture"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lecture" ADD CONSTRAINT "FK_05b264a75ceaafc30411e2e986e" FOREIGN KEY ("section_id") REFERENCES "section"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_detail" ADD CONSTRAINT "FK_a6ac5c99b8c02bd4ee53d3785be" FOREIGN KEY ("order_id") REFERENCES "order"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_detail" ADD CONSTRAINT "FK_78ae5dbb93417c8678f50b3e01a" FOREIGN KEY ("cart_id") REFERENCES "cart"("_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_detail" ADD CONSTRAINT "FK_828ec7997a3ace18f305f80948d" FOREIGN KEY ("course_id") REFERENCES "course"("_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cart" ADD CONSTRAINT "FK_f091e86a234693a49084b4c2c86" FOREIGN KEY ("user_id") REFERENCES "user"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cart" ADD CONSTRAINT "FK_ccbdf937aeec8a8e8fb3c454d60" FOREIGN KEY ("course_id") REFERENCES "course"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_quizz" ADD CONSTRAINT "FK_bfa27c32dff9368d5eb17987ce4" FOREIGN KEY ("user_id") REFERENCES "user"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_quizz" ADD CONSTRAINT "FK_73d50c934fd09938c1d393ef7b7" FOREIGN KEY ("quizz_id") REFERENCES "quizz"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "question" ADD CONSTRAINT "FK_7320b43dd91d88b143705930c0a" FOREIGN KEY ("exam_id") REFERENCES "exam"("_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "question" ADD CONSTRAINT "FK_564db71b43267fd9a0131bab62b" FOREIGN KEY ("quizz_id") REFERENCES "quizz"("_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_exam" ADD CONSTRAINT "FK_6bc59a5f8844254c8a6f95c121d" FOREIGN KEY ("user_id") REFERENCES "user"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_exam" ADD CONSTRAINT "FK_611c88152e7946bbff4581be895" FOREIGN KEY ("exam_id") REFERENCES "exam"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "blog" ADD CONSTRAINT "FK_08dfe0c802192ba0c499d4cdb9c" FOREIGN KEY ("user_id") REFERENCES "user"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_302d96673413455481d5ff4022a" FOREIGN KEY ("address_id") REFERENCES "address"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "category" ADD CONSTRAINT "FK_cc7f32b7ab33c70b9e715afae84" FOREIGN KEY ("category_id") REFERENCES "category"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions_permission" ADD CONSTRAINT "FK_b36cb2e04bc353ca4ede00d87b9" FOREIGN KEY ("roleId") REFERENCES "role"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "role_permissions_permission" ADD CONSTRAINT "FK_bfbc9e263d4cea6d7a8c9eb3ad2" FOREIGN KEY ("permissionId") REFERENCES "permission"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_roles_role" ADD CONSTRAINT "FK_09d115a69b6014d324d592f9c42" FOREIGN KEY ("user_id") REFERENCES "user"("_id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_roles_role" ADD CONSTRAINT "FK_4be2f7adf862634f5f803d246b8" FOREIGN KEY ("roleId") REFERENCES "role"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "user_roles_role" DROP CONSTRAINT "FK_4be2f7adf862634f5f803d246b8"`);
        await queryRunner.query(`ALTER TABLE "user_roles_role" DROP CONSTRAINT "FK_09d115a69b6014d324d592f9c42"`);
        await queryRunner.query(`ALTER TABLE "role_permissions_permission" DROP CONSTRAINT "FK_bfbc9e263d4cea6d7a8c9eb3ad2"`);
        await queryRunner.query(`ALTER TABLE "role_permissions_permission" DROP CONSTRAINT "FK_b36cb2e04bc353ca4ede00d87b9"`);
        await queryRunner.query(`ALTER TABLE "category" DROP CONSTRAINT "FK_cc7f32b7ab33c70b9e715afae84"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_302d96673413455481d5ff4022a"`);
        await queryRunner.query(`ALTER TABLE "blog" DROP CONSTRAINT "FK_08dfe0c802192ba0c499d4cdb9c"`);
        await queryRunner.query(`ALTER TABLE "user_exam" DROP CONSTRAINT "FK_611c88152e7946bbff4581be895"`);
        await queryRunner.query(`ALTER TABLE "user_exam" DROP CONSTRAINT "FK_6bc59a5f8844254c8a6f95c121d"`);
        await queryRunner.query(`ALTER TABLE "question" DROP CONSTRAINT "FK_564db71b43267fd9a0131bab62b"`);
        await queryRunner.query(`ALTER TABLE "question" DROP CONSTRAINT "FK_7320b43dd91d88b143705930c0a"`);
        await queryRunner.query(`ALTER TABLE "user_quizz" DROP CONSTRAINT "FK_73d50c934fd09938c1d393ef7b7"`);
        await queryRunner.query(`ALTER TABLE "user_quizz" DROP CONSTRAINT "FK_bfa27c32dff9368d5eb17987ce4"`);
        await queryRunner.query(`ALTER TABLE "cart" DROP CONSTRAINT "FK_ccbdf937aeec8a8e8fb3c454d60"`);
        await queryRunner.query(`ALTER TABLE "cart" DROP CONSTRAINT "FK_f091e86a234693a49084b4c2c86"`);
        await queryRunner.query(`ALTER TABLE "order_detail" DROP CONSTRAINT "FK_828ec7997a3ace18f305f80948d"`);
        await queryRunner.query(`ALTER TABLE "order_detail" DROP CONSTRAINT "FK_78ae5dbb93417c8678f50b3e01a"`);
        await queryRunner.query(`ALTER TABLE "order_detail" DROP CONSTRAINT "FK_a6ac5c99b8c02bd4ee53d3785be"`);
        await queryRunner.query(`ALTER TABLE "lecture" DROP CONSTRAINT "FK_05b264a75ceaafc30411e2e986e"`);
        await queryRunner.query(`ALTER TABLE "lecture_quizz" DROP CONSTRAINT "FK_2c90f00c429114649d5a0df9898"`);
        await queryRunner.query(`ALTER TABLE "comment" DROP CONSTRAINT "FK_bbfe153fa60aa06483ed35ff4a7"`);
        await queryRunner.query(`ALTER TABLE "comment" DROP CONSTRAINT "FK_c86c5b7d5079786fb840989975e"`);
        await queryRunner.query(`ALTER TABLE "user_course" DROP CONSTRAINT "FK_8abb4cbd80ac598dbe7c4dd8ce2"`);
        await queryRunner.query(`ALTER TABLE "user_course" DROP CONSTRAINT "FK_a17a0128f2f4fbb56ca04a07036"`);
        await queryRunner.query(`ALTER TABLE "course_bookmark" DROP CONSTRAINT "FK_d5619bd83409d0f260d9cd959f3"`);
        await queryRunner.query(`ALTER TABLE "course_bookmark" DROP CONSTRAINT "FK_fafd38e7eaaa2dc5b0ac841d935"`);
        await queryRunner.query(`ALTER TABLE "section" DROP CONSTRAINT "FK_7e12912705e3430a0bd74dad81f"`);
        await queryRunner.query(`ALTER TABLE "order" DROP CONSTRAINT "FK_199e32a02ddc0f47cd93181d8fd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4be2f7adf862634f5f803d246b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_09d115a69b6014d324d592f9c4"`);
        await queryRunner.query(`DROP TABLE "user_roles_role"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bfbc9e263d4cea6d7a8c9eb3ad"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b36cb2e04bc353ca4ede00d87b"`);
        await queryRunner.query(`DROP TABLE "role_permissions_permission"`);
        await queryRunner.query(`DROP TABLE "subject_group"`);
        await queryRunner.query(`DROP TABLE "subject"`);
        await queryRunner.query(`DROP TABLE "category"`);
        await queryRunner.query(`DROP TABLE "address"`);
        await queryRunner.query(`DROP TABLE "user"`);
        await queryRunner.query(`DROP TABLE "blog"`);
        await queryRunner.query(`DROP TYPE "public"."blog_status_enum"`);
        await queryRunner.query(`DROP TABLE "exam"`);
        await queryRunner.query(`DROP TABLE "user_exam"`);
        await queryRunner.query(`DROP TABLE "question"`);
        await queryRunner.query(`DROP TYPE "public"."question_answer_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."question_question_level_enum"`);
        await queryRunner.query(`DROP TABLE "quizz"`);
        await queryRunner.query(`DROP TABLE "user_quizz"`);
        await queryRunner.query(`DROP TABLE "cart"`);
        await queryRunner.query(`DROP TABLE "order_detail"`);
        await queryRunner.query(`DROP TABLE "lecture"`);
        await queryRunner.query(`DROP TYPE "public"."lecture_lecture_type_enum"`);
        await queryRunner.query(`DROP TABLE "lecture_quizz"`);
        await queryRunner.query(`DROP TABLE "comment"`);
        await queryRunner.query(`DROP TABLE "course"`);
        await queryRunner.query(`DROP TABLE "user_course"`);
        await queryRunner.query(`DROP TABLE "course_bookmark"`);
        await queryRunner.query(`DROP TABLE "section"`);
        await queryRunner.query(`DROP TABLE "order"`);
        await queryRunner.query(`DROP TYPE "public"."order_payment_method_enum"`);
        await queryRunner.query(`DROP TABLE "role"`);
        await queryRunner.query(`DROP TABLE "permission"`);
    }

}
